services:
  nextjs-app:
    container_name: nextjs-app
    build:
      context: ./nextjs-frontend
      target: dev
      dockerfile: Dockerfile
    volumes:
        - ./nextjs-frontend:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
    networks:
      - app-network
  spring-app:
    container_name: spring-app
    build:
      context: ./spring-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["java", "-jar", "target/spring-backend-0.0.1-SNAPSHOT.jar"]
    networks:
      - app-network
networks:
  app-network:
    driver: bridge