services:
  nextjs-app:
    build:
      context: ./nextjs-frontend
      target: dev
      dockerfile: Dockerfile
    volumes:
        - ./nextjs-frontend:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"